apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ghoj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ghoj
    app.kubernetes.io/part-of: tkrw-pr712-0075-0075-app
  name: devfile-sample-ghoj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ghoj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ghoj
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0075-tenant/tkrw-pr712-0075-0075-app/devfile-sample-ghoj@sha256:bff3b33af5bdc59841ffc33982cafc51d2347f3e76b127f646c69e986154e107
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
